[default.extend-identifiers]
# software.md
snd_hda_intel = "snd_hda_intel"
DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING = "DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING"
"ba" = "ba"

[files]
extend-exclude = [
    "Its-Just-Nans/bits/*",
    "Its-Just-Nans/data/*",
    "Its-Just-Nans/website-articles/*",
    "Its-Just-Nans/others-articles/*",
]
